# Generated by Django 6.0.3 on 2026-04-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='user',
            new_name='seller_user',
        ),
    ]
