# Generated by Django 6.0.3 on 2026-05-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_orderitem_status'),
        ('users', '0004_remove_review_image_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
            preserve_default=False,
        ),
    ]
