# Generated by Django 6.0.3 on 2026-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=10, null=True),
        ),
    ]
