# Generated by Django 6.0.3 on 2026-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_cancel_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
