# Generated by Django 6.0.3 on 2026-09-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_is_cancel_acknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancellation Requested', 'cancellation Requested'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
